apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: kube-web-view
spec:
  selector:
    application: kube-web-view
  type: NodePort
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
