apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: default
  labels:
    app: test-app
    prometheus: prometheus-test-app-prometheus
spec:
  selector:
    matchLabels:
      # app: prometheus
      app: test-app
  endpoints:
  - port: web
    interval: 10s
  namespaceSelector:
    matchNames:
      - default